import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// _app.js hoặc _app.tsx
import 'bootstrap/dist/css/bootstrap.min.css';
import '../app/globals.css'; // Đảm bảo rằng bạn có tệp này để thêm các style tùy chỉnh khác
import Header from "@/components/app.header";
import Footer from "@/components/app.footer";
import { Container } from "react-bootstrap";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Header/>
       <Container>
        {children}
      
        </Container>
        <Footer/>
        <ToastContainer />
        </body>
    </html>
  );
}
